import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400","600", "700", "800"],
});

export const metadata = {
  title: "KnowledgeHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={inter.className}
    >
      <body className="bg-background text-foreground">
        <Providers>
        <Navbar></Navbar>
        {children}
        <ToastContainer />
        <Footer></Footer>
        </Providers>
        </body>
    </html>
  );
}
